### ISSUE TITLE
Data visualization of stocks

### ISSUE THREAD

**Issue by geetika001** [smridhiwho/IEEEHacksML-DL#3]
Hey @smridhiwho I have added this project in PR #2 .please review and do accept the PR.
Let me know if any changes required.

**Comment by smridhiwho** [comment]
I have reviewed your PR, however, your contribution is not in our desired format. Please make sure you also include a dataset folder and an 'Images' folder. Also, the readme should include the goal of the project, some introduction of the dataset and its link, accuracy, and your name. Refer to our Readme for precise instructions.

**Comment by geetika001** [comment]
Hey @smridhiwho .I have added the dataset's link in the code and README itself. Besides this,I'm adding the images in a separate folder(which have come as an observation and also shown in jupyter notebook)
Adding more about the Project in README related to stocks.However,since this project is based on fata visualization,there's no concept of accuracy.I have still added statistics for all the observations in README and the jupyter notebook also.Please check once again.
